version: 2
jobs:
  build:
    docker:
      - image: osresearch/musl-cross:38e52db
    steps:
      - checkout

      - run:
          name: Bootstrap make
          command: |
            make -j4 bootstrap

      - run:
          name: qemu-linuxboot-edk2
          command: |
            ./build/make-4.2.1/make \
                CROSS=/cross/bin/x86_64-linux-musl- \
                BOARD=qemu-linuxboot \
                `/bin/pwd`/build/linuxboot-git/build/qemu/.configured \
                # Run first to avoid too many processes

      - store-artifacts:
          path: build/qemu-linuxboot/linuxboot.rom
      - store-artifacts:
          path: build/qemu-linuxboot/hashes.txt



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
